# Generated by Django 2.1.2 on 2018-11-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_casa',
        ),
    ]
