# Generated by Django 2.1.2 on 2018-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=10)),
                ('necesita_receta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20)),
                ('med_id', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=40)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
        ),
    ]
