# Generated by Django 2.1.2 on 2018-11-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_medicamento_medicamentousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentousuario',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='medicamentousuario',
            name='nombre',
        ),
    ]
