# Generated by Django 2.1.2 on 2018-11-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_auto_20181113_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentousuario',
            name='id',
        ),
        migrations.AddField(
            model_name='medicamentousuario',
            name='key_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
