# Generated by Django 2.1.2 on 2018-11-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20181114_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('numero_tarjeta', models.IntegerField()),
                ('banco', models.CharField(max_length=30)),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('clave_secreta', models.IntegerField()),
            ],
        ),
    ]
