# Generated by Django 2.1.2 on 2018-11-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0008_auto_20181114_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentousuario',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
